name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore world
        uses: actions/download-artifact@v4
        with:
          name: minecraft-world
          path: .
        continue-on-error: true

      - name: Install Java
        run: sudo apt update && sudo apt install openjdk-17-jre -y
        
      - name: Start Minecraft Server
        run: |
          bash server.sh &
          sleep 20
          
      - name: Start Playit Tunnel
        run: |
          curl -L https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64 -o playit
          chmod +x playit
          ./playit &
          sleep 21000

      - name: Save world
        uses: actions/upload-artifact@v4
        with:
          name: minecraft-world
          path: |
            world
            world_nether
            world_the_end
